# Generated by Django 5.0.6 on 2024-06-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Дата_создания',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Описание',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Укажите_Дату',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Статус',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Название',
            new_name='title',
        ),
    ]
